sudo: false

language: rust

rust:
  - stable

script:
  - ./pleasew test --plain_output

before_install: |
 cat <<EOF > .plzconfig.local
 [build]
 path = $PATH:$HOME/fst/bin

 [go]
 goroot = $GOROOT

 [cpp]
 cctool = g++-4.8
 defaultoptcflags = --std=c++11 -O2 -DNDEBUG -I $HOME/fst/include -L $HOME/fst/lib -Wl,-rpath $HOME/fst/lib

 [cache]
 dir = $HOME/plz-cache

 EOF

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - binutils
      - gcc-4.8
      - g++-4.8
      - unzip

install:
  - pip install --user cffi>=1.5.0

git:
  depth: 3

cache:
  directories:
    - $HOME/plz-cache
    - $HOME/.please
