version: 2
jobs:
   build:
     working_directory: ~/pleasings
     docker:
       - image: thoughtmachine/pleasings:latest
     steps:
       - checkout
       - run:
           name: Build
           command: plz build
       - run:
           name: Test
           command: plz test
       - store_test_results:
           path: plz-out/log/test_results.xml
